### PR TITLE
Add Feed, an iterator adapter that lets one set multiple elements to be yielded next by itself

### PR DESCRIPTION
**Pull request by flo-l**
Remake of #22, it's a new struct now!

I borrowed the name from ruby, suggestions are as always more than welcome!

### CODE REVIEW

**Comment by bluss** [comment]
Looks fine. Where is the Ruby version? Is there precedent for the way multiple values are fed? I would have expected them to be pushed to the front.

**Comment by flo-l** [comment]
The ruby version: http://ruby-doc.org/core-1.9.3/Enumerator.html#method-i-feed

It supports just one element.

Yeah I also wasn't sure about the ordering. But I decided to push it to the back of the feed-vec so that you can write the following:

```rust
use itertools::Itertools;
let v: Vec<u8> = vec![];
let mut it = v.feedable();
it.feed(2u8);
it.feed(3u8);
assert_eq!(it.next(), 2u8);
assert_eq!(it.next(), 3u8);
```

My mental model is the iterator being a pipe into which I throw items...the one I throw in first comes out first. But I can also change this if you prefer!

**Comment by bluss** [comment]
Oh so the Ruby feed doesn't do this at all. It's like `.send()` on a generator in Python, it feeds a value back into a coroutine. That kind of thing doesn't exist in Rust.

So I think we should rename this thing.

Anyway about the ordering, the reverse order feels more natural.

**Comment by flo-l** [comment]
Ordering reversed..

Any suggestions for the new name? PutBackMult sounds a bit clumsy :(

**Comment by bluss** [comment]
What about PutBackN and method .put_back?

**Comment by flo-l** [comment]
ping @bluss 

sorry it took me some time to react!

**Comment by bluss** [comment]
Looks good. I'll merge it when I can (I'm away tomorrow probably).

Can I ask you to squash the fixes together (if you want) and actually remove the method in the Itertools trait? Some adaptors just aren't worth using a method on IMO. PutBack doesn't have a method, and I think it's logical given that you never method chain after you create it. It is not like map() where you want to create a pipeline.

**Comment by flo-l** [comment]
reopened as #29

**Pull request closed without merging**
