### PR TITLE
Fold options

### PR DESCRIPTION
**Pull request by marcusklaas**
Closes https://github.com/bluss/rust-itertools/issues/65.

### CODE REVIEW

**Comment by bluss** [comment]
Looks good! No version bumps in PRs please though.

**Comment by marcusklaas** [comment]
Reverted the version bump. Apologies for the delay.

**Comment by bluss** [comment]
No worries about time.

Can you fix the test failures? see the travis run on the PR. It's just a missing mut in the example, it looks like. Thanks!

**Comment by marcusklaas** [comment]
Fixed!

**Comment by bluss** [comment]
Thanks!

**Pull request merged**
