### PR TITLE
[WIP] implement sliding_windows()

### PR DESCRIPTION
**Pull request by flo-l**
This is the code for #64.

@bluss How do you feel about the design?

I'll write docs as soon as the design is approved.

The code as written now disallows the following by runtime checks:

```rust
let mut storage: SlidingWindowStorage<u32> = SlidingWindowStorage::new(3)
let iter = (0..100).sliding_windows(storage);

// a must go out of scope before the second call to iter.next()
let a = iter.next();
let b = iter.next();

// storage may not be dropped before the last Window, in this case a
let mut storage: SlidingWindowStorage<u32> = SlidingWindowStorage::new(3);
let a = {
    let iter = (0..100).sliding_windows(storage);
    iter.next()
};
std::mem::drop(storage);
// a points to garbage now
```

In either case the code ```panic!()```s with an error message.

### CODE REVIEW

**Comment by flo-l** [comment]
I think I hit some [breaking-change] related behaviour, but it seems to compile on stable at least :p

**Comment by bluss** [comment]
Thanks. I'll poke a bit at the code. I hope it can be done a lot safer with using Cell and references.

**Comment by bluss** [comment]
Ok I sent some edits to your branch as a PR.

The clean way to implement custom interior mutability is via UnsafeCell; also splitting storage and iterator enables the much safer pattern of borrowing the storage in each iterator element. This is all quite neat.

However, I remain sceptical of an iterator that panics if multiple elements live at the same thing; it will break when put into some iterator adaptors. So it's certainly interesting and cool. All solutions have downsides.

**Comment by bluss** [comment]
Maybe it would be maximally conservative, but we could consider using a Result type, returning Error if there is a borrowing error. It's a bit ridiculous, but it puts the error handling over in the user's court :/

**Comment by flo-l** [comment]
I like the Result idea. I found it scary how invisible the whole unsafe borrowing thing was after I had cleaned up the api a bit!

I'll go ahead and merge your PR (thanks btw) and continue my work atop your changes. The Cell types make it a lot less scary ;)

**Comment by bluss** [comment]
Yes it's a lot better :) Cell is always completely safe to use, while UnsafeCell must be used with care.

**Comment by bluss** [comment]
Note that something that is mutated behind a shared reference (&-pointer) *must* be inside an `UnsafeCell`

**Comment by flo-l** [comment]
Is it desired that the adapter throws away the last value of the underlying iterator and returns ```None``` forever as soon as it encounters a borrow error? (Actually it returns ```Some(Err(()))``` first and then ```None```)

**Comment by flo-l** [comment]
Wouldn't it be cool to give the user a chance to recover from a borrow error?

**Comment by bluss** [comment]
Right, that doesn't sound good. Better to check up front. I don't think recovering from borrow error is something that will happen in actual code; encountering it is evidence for a bug. With that reasoning, it really is borderline on whether it should panic or not.

**Comment by flo-l** [comment]
I can't think of a realistic scenario where a borrow error is expected. Maybe there is some crazy code possible which does all the borrowing dynamically etc. etc. but that's a niche use case. Especially as window is neither send nor sync, so scary thread constructions are impossible. In that case a cloning implementation of windows wouldn't be a huge performance loss anyway I guess.

But I like how result makes it explicit that such an error can happen. It's quite likely that some other adapter messes things up.

However I'm leaning towards the panic solution because it makes user code more compact and result doesn't give the user a real alternative to panicking. Also if the user messes up a panic probably occurs early in the development process anyway as it's unusual to call next() just in rare cases twice.

**Comment by flo-l** [comment]
I'll reopen it soonish, I just don't want to develop on master

**Comment by bluss** [comment]
great

**Pull request closed without merging**
