### PR TITLE
Update adaptors.rs

### LINKED ISSUE #118: bound function not correct
See here: https://github.com/bluss/rust-itertools/blob/master/src/adaptors.rs#L142

Isn't it missing the case `self.phase && a < b`?

### PR DESCRIPTION
**Pull request by kindlychung**
fixes lower bound error

Fixes #118

### CODE REVIEW

**Comment by bluss** [comment]
Thanks for reading & fixing this code that I thought nobody would care about. This can indeed be better. Quickcheck tests should use an exact test for interleave_shortest. Can you please add the testcase from your bug report though?

**Comment by kindlychung** [comment]
Sure, can I just use `#[test]`?

**Comment by bluss** [comment]
Yes

**Comment by bluss** [comment]
Thanks, merged with test.

**Pull request merged**
